### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fulldecent**

### CODE REVIEW

**Comment by fulldecent** [comment]
Is this project accepting PR contributions?

**Comment by aaronfagan** [comment]
hi @fulldecent - it certainly is! I apologies ont he delay - wasnt paying attention to how popular this project has become!

**Comment by aaronfagan** [comment]
In the meantime, im going to close this PR as I dont see any changes. If you would like to discuss further, ive commented on your Issue you posted. In addition, feel free to contact me directly through my website.

Cheers!

**Comment by fulldecent** [comment]
The change was just to correct "Github" => "GitHub"

**Comment by aaronfagan** [comment]
@fulldecent Thanks - missed that. Corrected!

**Pull request merged**
